### ISSUE TITLE
Make hosts of microservices / REST-APIs configurable by environment variables

### ISSUE THREAD

**Issue by opensemanticsearch** [opensemanticsearch/open-semantic-etl#100]
Make hosts of microservices / REST-APIs like Solr, Tika, spaCy and Open Semantic Entity Search API configurable by environment variables, so we can configure them dynamic in/by Docker config without modifications of config files in containers.

**Comment by Mandalka** [comment]
Implemented config of RabbitMQ broker host by environment variable OPEN_SEMANTIC_ETL_MQ_BROKER

**Comment by Mandalka** [comment]
Implemented config of Tika server host by environment variable OPEN_SEMANTIC_ETL_TIKA_SERVER

**Comment by Mandalka** [comment]
Implemented config of Solr server host by environment variable
OPEN_SEMANTIC_ETL_SOLR

**Comment by Mandalka** [comment]
Implemented config of spacy services by environment variable
OPEN_SEMANTIC_ETL_SPACY_NER

**Comment by Mandalka** [comment]
Implemented config of Neo4j host by environment variable
OPEN_SEMANTIC_ETL_NEO4J_HOST

**Comment by Mandalka** [comment]
Implemented config of tagging metadata host by environment variable
OPEN_SEMANTIC_ETL_METADATA_SERVER
