### ISSUE TITLE
Twitter scraper

### ISSUE THREAD

**Issue by opensemanticsearch** [opensemanticsearch/open-semantic-etl#101]
Open Semantic ETL module for import of Tweets by Twint https://github.com/twintproject/twint

**Comment by Mandalka** [comment]
Implemented optional indexing of linked web pages in tweets https://github.com/opensemanticsearch/open-semantic-search/issues/238

**Comment by Mandalka** [comment]
Implemented by https://github.com/opensemanticsearch/open-semantic-etl/blob/master/src/opensemanticetl/etl_twitter_scraper.py
