### ISSUE TITLE
No additional ETL errors by following plugins, if main plugin failed

### ISSUE THREAD

**Issue by opensemanticsearch** [opensemanticsearch/open-semantic-etl#104]
We dont need additional ETL errors for plugins like enhance_contenttype_group, enhance_warc  and so on, if error is result of yet statused failure of main plugin like Tika extraction.

**Comment by Mandalka** [comment]
Implemented for plugin enhance_contenttype_group

**Comment by Mandalka** [comment]
Implemented for plugin enhance_warc

**Comment by Mandalka** [comment]
Implemented for plugin enhance_rdf

**Comment by Mandalka** [comment]
Implemented for optional plugin enhance_pdf_ocr

**Comment by Mandalka** [comment]
Implemented for optional plugin enhance_pdf_page
