### ISSUE TITLE
Handling Maltego files correctly

### ISSUE THREAD

**Issue by NetwarSystem** [opensemanticsearch/open-semantic-etl#109]
The Maltego link analysis package writes files in two formats. Older files have the extension .mtgx, while newer ones have the extension .mtgl. I placed one of each type in a directory and indexed it. The .mtgl file processed as expected - I can search on the entities inside it. The mtgx file made a terrible mess - it got the file itself, then it produces an additional OSS entry for each entity in the file.

Is there a way to control how deeply the system digs into the .mtgx files? I can provide copies of both types of file if that would help. If you want me to do some additional work to isolate this problem that is fine - just give me a hint of where to start looking.

**Comment by NetwarSystem** [comment]
I tried with just .mtgl files and it does the same thing - lots and lots of entries for Maltego entities, which is not what we want.

How do I stop ETL from digging into those two file types?

**Comment by opensemanticsearch** [comment]
Please send me diffenrent example files, so i can look what ETL does.
Maybe the file format is a ZIP, so the zip extractor plugin will handle it additionally to Tika (this can be blacklisted like done for Office documents) so each file inside the zip is an additional file.

**Comment by NetwarSystem** [comment]
Sorry for the huge delay - I put a sample MTGL and MTGX file in this Dropbox link.

https://www.dropbox.com/sh/h1s07slajufptmp/AAATASWPOWi_f18Ljrlli7XGa
