### ISSUE TITLE
Plugin core class

### ISSUE THREAD

**Issue by opensemanticsearch** [opensemanticsearch/open-semantic-etl#112]
Fore more DRY and reusable code (in growing count of plugins) and easier development of new plugins, migrate often used code parts and functionality like filtering for/running on certain content type or get text data from all fields for text analysis to a plugin core class which can be inherited.

**Comment by Mandalka** [comment]
Implemented Plugin core class in etl_plugin_core.py

**Comment by Mandalka** [comment]
Migrated enhance_pdf_ocr to inherit from plugin core.

**Comment by Mandalka** [comment]
Migrated enhance_pdf_page to inherit from plugin core.

**Comment by Mandalka** [comment]
Migrated enhance_pdf_page_preview to inherit from plugin core

**Comment by Mandalka** [comment]
Migrated enhance_warc to inherit from plugin core

**Comment by Mandalka** [comment]
Migrated enhance_pst to inherit from plugin core

**Comment by Mandalka** [comment]
Migrated enhance_entity_linking to inherit from plugin core.

**Comment by Mandalka** [comment]
Migrated enhance_extract_email to plugin core lib.

**Comment by Mandalka** [comment]
Migrated enhance_regex to plugin core lib.

**Comment by Mandalka** [comment]
Migrated enhance_extract_phone to plugin core lib.

**Comment by Mandalka** [comment]
Migrated enhance_extract_hashtags
