### ISSUE TITLE
ETL runtime stats more granular

### ISSUE THREAD

**Issue by opensemanticsearch** [opensemanticsearch/open-semantic-etl#114]
Make ETL runtime stats more granular / for each plugin (analog to runtime stats of text extraction by Tika), so we can easier analyze stats for each plugin / tool / enrichment / enhancement stage.

**Comment by Mandalka** [comment]
Implemented separated runtime stat for each plugin to integer fields etl_pluginname_time_millis_i which are shown in UI in preview tab "Document processing (ETL)"
