### ISSUE TITLE
Move technical metadata fieldnames to separated config

### ISSUE THREAD

**Issue by opensemanticsearch** [opensemanticsearch/open-semantic-etl#117]
Move list of technical metadata fieldnames like pdf:docinfo:creator_tool and so on from plugin enhance_multilingual to separated blacklist config, so reusable by other plugins like plugin core method gettext()

**Comment by Mandalka** [comment]
Separated fieldname config to /etc/opensemanticsearch/blacklist/textanalysis/

**Comment by Mandalka** [comment]
These blacklists now used by text analysis plugins based on plugin core, too.
