### ISSUE TITLE
PDF OCR plugin: Use same tesseract options like tika-server

### ISSUE THREAD

**Issue by opensemanticsearch** [opensemanticsearch/open-semantic-etl#119]
Use same tesseract options like tika-server in enhance_pdf_ocr plugin so both can use same OCR cache results

**Comment by Mandalka** [comment]
I close this issue, since Tika seems to convert/optimize the image(s) before OCR, so input and hash not the same for same embedded image files and the plugin is not default anymore, since our new default settings using Tikas OCR now with our new tesseract-ocr-cache.
