### ISSUE TITLE
handle filenames with special characters and/or accents

### ISSUE THREAD

**Issue by lunatic4ever** [opensemanticsearch/open-semantic-etl#12]
the indexing process throws an error when the filename contains non-url acceptable characters.
If i rename the file (using iconv and sed) to remove invalid characters and replace accented characters with normal ascii characters it is no problem.

I have changed one line in the file enhance_extract_text_tika_server.py and that seems to work...
from
`#curl.setopt(curl.HTTPPOST, [('fileupload', (curl.FORM_FILE, filename, curl.FORM_FILENAME, filename))])`
to               
` curl.setopt(curl.HTTPPOST, [('fileupload', (curl.FORM_FILE, filename.encode('utf-8'), curl.FORM_FILENAME, filename.encode('utf-8') ))])`

**Comment by Mandalka** [comment]
Thank you very much. I [added](https://github.com/opensemanticsearch/open-semantic-etl/commit/17c764a0f08ef756712afe716457b6425356f740) this encoding again, even if now Python3 base and so i hope Curl or PyCurl will do some maybe needed urlencoding itselfes / right.

My tests with special chars in filenames worked.
