### ISSUE TITLE
Exception with plugin enhance_zip : Unicode-objects must be encoded before hashing

### ISSUE THREAD

**Issue by alaw005** [opensemanticsearch/open-semantic-etl#13]
When I run this command 
> opensemanticsearch-index-dir /mnt/tmp
I get the following error
> Exception while data enrichment of /mnt/tmp/Book1.xlsx with plugin enhance_zip: Unicode-objects must be encoded before hashing

**Comment by Mandalka** [comment]
Upgraded to Python 3
