### ISSUE TITLE
Index whole website by sitemap

### ISSUE THREAD

**Issue by opensemanticsearch** [opensemanticsearch/open-semantic-etl#14]
Index a whole website by sitemap.xml

**Comment by Mandalka** [comment]
New command line tool: opensemanticsearch-index-sitemap

**Comment by Mandalka** [comment]
Implemented Django UI, so you can easier configure/manage sitemaps via the datasources web UI.

**Comment by Mandalka** [comment]
Todo: Indexing URLs in subsitemaps by seperation of sitemaps urls and webpage urls and recursion of sitemaps.

**Comment by Mandalka** [comment]
Supports now recursive processing of (sub)sitemaps if a sitemapindex instead of an urlset.
