### ISSUE TITLE
Docker build fails, Missing dependency py2neo==3.1.2

### ISSUE THREAD

**Issue by jmservera** [opensemanticsearch/open-semantic-etl#143]
The py2neo project does not distribute this version anymore.

By now there is a workaround, you can modify the requirements.txt and replace the py2neo requirement with the link to the archived release: https://github.com/technige/py2neo/archive/refs/tags/py2neo-3.1.2.zip

**Comment by Mandalka** [comment]
Is resolved / migrated to new release by work in https://github.com/opensemanticsearch/open-semantic-search/issues/390
