### ISSUE TITLE
Docker container fails with AttributeError: 'Celery' object has no attribute 'worker_main'

### ISSUE THREAD

**Issue by Dave3o3** [opensemanticsearch/open-semantic-etl#145]
The image builds successfully but the service exits with:

```
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/opensemanticetl/tasks.py", line 228, in <module>
    app.worker_main()
AttributeError: 'Celery' object has no attribute 'worker_main'
```

**Comment by jamieJames45** [comment]
**workaround** 
_Disclaimer,  unsure what knock on effects swapping out the celery version will have, as I am just running this stack for the first time, and this is what I did to get past the issue._ 

more info on the actual cause can be found here : 
https://github.com/celery/celery/issues/6404

edit open-semantic-search/src/open-semantic-etl/src/opensemanticetl/requirements.txt, 
specify version number for the celery requirement:

celery==4.4.7

in the open-semantic-search/src/open-semantic-etl/ folder, run 
"docker build -t opensemanticsearch/open-semantic-etl ."

then go back to the project root, and docker compose up should work properly

**Comment by Mandalka** [comment]
Fixed by https://github.com/opensemanticsearch/open-semantic-search/issues/375
