### ISSUE TITLE
Group content types to user friendly labels

### ISSUE THREAD

**Issue by opensemanticsearch** [opensemanticsearch/open-semantic-etl#15]
Aggregate similar content types to groups with user friendly labels like "spreadsheet" or "text document" that can be used as filter / facet.

**Comment by Mandalka** [comment]
Implemented in new ETL plugin [enhance_contenttype_group.py](https://github.com/opensemanticsearch/open-semantic-etl/blob/master/src/opensemanticetl/enhance_contenttype_group.py)
