### ISSUE TITLE
enhance_extract_text_tika_server.py fails unless headers=headers commented out

### ISSUE THREAD

**Issue by jgillum** [opensemanticsearch/open-semantic-etl#150]
Extracting text using Tika fails (error 400) unless line 142 is commented out in enhance_extract_text_tika_server.py:

```
parsed = parser.from_file(
                    filename=filename,
                    serverEndpoint=tika_server,
                    #headers=headers,
                    requestOptions={'timeout': 60000})
```

I don't understand why that fixes it; perhaps it's something to do with the latest Python packages and Tika (verison 2.1.0)?  Running on Ubuntu 20.

**Comment by Mandalka** [comment]
Issue with Tika 2.x which doesn't accept X-Tika-OCRTesseractPath anymore: https://github.com/opensemanticsearch/open-semantic-search/issues/389

**Comment by opensemanticsearch** [comment]
Fixed / migrated to Tika 2.x by #142 (new release next days).
