### ISSUE TITLE
Extract amounts of money

### ISSUE THREAD

**Issue by opensemanticsearch** [opensemanticsearch/open-semantic-etl#156]
Additional to machine learning NER approach add ontology- and regex-based extraction of amounts of money (https://github.com/opensemanticsearch/open-semantic-search/issues/399).

**Comment by Mandalka** [comment]
Plugin: https://github.com/opensemanticsearch/open-semantic-etl/blob/master/src/opensemanticetl/enhance_extract_money.py

**Comment by Mandalka** [comment]
Todo: Recognize if number parts as string like "thousand", "million" and "billion".

**Comment by Mandalka** [comment]
Integrated https://github.com/jaidevd/numerizer
