### ISSUE TITLE
nonsymmetry between opensemanticsearch-index-file and opensemanticsearch-delete

### ISSUE THREAD

**Issue by dhyams** [opensemanticsearch/open-semantic-etl#19]
I have the following mapping set:

config['mappings'] = {
   "/var/www/html": "http://192.168.20.102"
}

If I manually add in a file to the index with this:

opensemanticsearch-index-file /var/www/html/documents/a.pdf

and then try to delete like this:

opensemanticsearch-delete /var/www/html/documents/a.pdf

The deletion does not occur, because the document has been added in with its URI, not the filename.  I find this behavior a little unexpected.  Deleting with the URI does work:

opensemanticsearch-delete http://192.168.20.102/documents/a.pdf

Not sure if this is the behavior that is desired, but given that it looks like most of the tools are supposed to work with a filename or URI, it seems like the first form should work as well.

**Comment by Mandalka** [comment]
Now you can use the file system filename instead of mapped URI, too.

Implemented support of filenames (and its mapping config) in etl_delete.py (opensemanticsearch-delete) by https://github.com/opensemanticsearch/open-semantic-etl/commit/6b37bca310021abe09a1bfffcb651ec45f63c6b8.
