### ISSUE TITLE
Dedupe content type knowledge graph

### ISSUE THREAD

**Issue by Mandalka** [opensemanticsearch/open-semantic-etl#24]
Dedupe content type, so the content type value "knowledge graph" will be indexed and printed only once, even if aggregated from multiple RDF data sources.

**Comment by Mandalka** [comment]
Done in enhance_rdf.py by setting content_type instead of add.

Todo: Do not set content_type to knowledge graph if triple is describing existent file with other content type instead of another knowledge graph triple.

For example switch again to add, if import of RDF will be done at once for each URI instead for each triple, like it is done in the ontologies manager.

**Comment by opensemanticsearch** [comment]
Resolved by https://github.com/opensemanticsearch/open-semantic-etl/issues/42
