### ISSUE TITLE
Named Entities Recognition in additional content fields like OCR

### ISSUE THREAD

**Issue by Mandalka** [opensemanticsearch/open-semantic-etl#26]
Do Namend Entities Recognition and Named Entities Extraction by Regex in additional content fields like OCR content, too

**Comment by Mandalka** [comment]
Named entity extraction / entity recognition / entity linking by lists of names, thesaurus and ontologies works now for all fields.

**Comment by opensemanticsearch** [comment]
NER by ML for OCR was implemented, too long time ago, so closing this old ticket.

New Issue https://github.com/opensemanticsearch/open-semantic-etl/issues/112 should solve this more flexible and more general for new additional fields and all plugins.
