### ISSUE TITLE
Index RDF graphs more granular

### ISSUE THREAD

**Issue by Mandalka** [opensemanticsearch/open-semantic-etl#4]
At the moment graph files (RDF) are indexed as one file, so you can only find whole graph files while fulltext search, analysis or text mining.

An more granular import will allow you to search and filter for single entities (URIs) and fields/facets (properties).

**Comment by Mandalka** [comment]
First draft of documentation: http://www.opensemanticsearch.org/connector/rdf

**Comment by opensemanticsearch** [comment]
Now for each URI/subject in RDF knowledge graph file different document including its properties/predicates and values/objects by [src/etl/enhance_etl.py](https://github.com/opensemanticsearch/open-semantic-etl/commit/2c7374e59ea08afad681ea63d855ba5c5989a127)
