### ISSUE TITLE
RDF knowledge graph import: Index all properties / triples of each entity / subject at once

### ISSUE THREAD

**Issue by opensemanticsearch** [opensemanticsearch/open-semantic-etl#42]
For better performance of RDF knowledge graph import index all properties/triples of each entity / subject at once, not every single triple.

**Comment by Mandalka** [comment]
With https://github.com/opensemanticsearch/open-semantic-etl/commit/d8edb1ca099274654d3b6c71da4251e383305047 now much faster import of RDF knowledge graphs.
