### ISSUE TITLE
add application/vnd.etsi.asic-e+zip  to enhance_contenttype_group

### ISSUE THREAD

**Issue by hillar** [opensemanticsearch/open-semantic-etl#44]
please add "application/vnd.etsi.asic-e+zip" as "Electronic Signature Container" to enhance_contenttype_group.py

see:
https://www.iana.org/assignments/media-types/application/vnd.etsi.asic-e+zip
http://www.etsi.org/deliver/etsi_ts/102900_102999/102918/01.03.01_60/ts_102918v010301p.pdf
https://www.id.ee/?id=34336
https://www.id.ee/index.php?id=36110

**Comment by Mandalka** [comment]
Will add this for next release.
