### ISSUE TITLE
'export_elasticsearch' object has no attribute 'commit'

### ISSUE THREAD

**Issue by hillar** [opensemanticsearch/open-semantic-etl#45]
'export_elasticsearch' object has no attribute 'commit'

should that do ...

def commit(self):
   return

**Comment by Mandalka** [comment]
Added in https://github.com/opensemanticsearch/open-semantic-etl/commit/0f8ecc1b7a63a2d513c3fcdc168589ddf6a29ec9 to make Elastic Search exporter compatible with ETL connectors that call explicit commit.
