### ISSUE TITLE
Export entities and connections to Neo4j 

### ISSUE THREAD

**Issue by opensemanticsearch** [opensemanticsearch/open-semantic-etl#47]
Write entities from Named Entity Recognition and connections to Neo4j graph database, so we can visualize, analyze and browse indirect connections of persons, organizations, locations ...

**Comment by Mandalka** [comment]
Export of named entities to Neo4j graphdatabase to analyze and explore indirect connections over multiple documents or emails by new plugin export_neo4j.py

![Neo4j graph visualization](https://user-images.githubusercontent.com/1010780/36641990-31cf18d6-1a39-11e8-9c7f-f3fbdb40bd25.png)
