### ISSUE TITLE
commit to solr has hardcoded core name "core1"

### ISSUE THREAD

**Issue by hillar** [opensemanticsearch/open-semantic-etl#48]
if solr core name is in config file something else than *"core1"* 
then etl_file.py ends with 404 from solr server

the 'post' req to /solr/**corenamefromconfigfile**/update works as expected and solr server answers with 200
but 'commit' req fails as uri is __/solr/**core1**/update__ not /solr/**corenamefromconfigfile**/update

it seems that in "commit" all  (host,core,verbose) are init'ed as default

https://github.com/opensemanticsearch/open-semantic-etl/blob/3fa9fe770d90804d25adc58afc572c5c1ba71f7e/src/opensemanticetl/export_solr.py#L12

https://github.com/opensemanticsearch/open-semantic-etl/blob/3fa9fe770d90804d25adc58afc572c5c1ba71f7e/src/opensemanticetl/export_solr.py#L223

--------
```
root@osse:/opt/etl/python# grep solr ../config/etl
config['export'] = 'export_solr'
config['solr'] = 'http://127.0.0.1:8983/solr/'
config['index'] = 'solrdefalutcore'

root@osse:/opt/etl/python# python3 etl_file.py --verbose -c ../config/etl /etc/hostname 
..
Sending update request to http://127.0.0.1:8983/solr/solrdefalutcore/update
[{"title"..
Commiting cached or open transactions to index
Sending commit request to http://localhost:8983/solr/core1/update?commit=true ()nd self.verbose is also not set
Traceback (most recent call last):
  File "etl_file.py", line 241, in <module>
    connector.commit()
  File "/opt/etl/python/etl.py", line 294, in commit
    self.exporter.commit()
  File "/opt/etl/python/export_solr.py", line 227, in commit
    request = urllib.request.urlopen( uri )
  File "/usr/lib/python3.5/urllib/request.py", line 163, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/lib/python3.5/urllib/request.py", line 472, in open
    response = meth(req, response)
  File "/usr/lib/python3.5/urllib/request.py", line 582, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib/python3.5/urllib/request.py", line 510, in error
    return self._call_chain(*args)
  File "/usr/lib/python3.5/urllib/request.py", line 444, in _call_chain
    result = func(*args)
  File "/usr/lib/python3.5/urllib/request.py", line 590, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 404: Not Found
```

**Comment by Mandalka** [comment]
Config should be used since https://github.com/opensemanticsearch/open-semantic-etl/commit/0101c652cdb3b8e3a02afac3602eb91cb1859ce3#diff-a7b8db21f1d7da551ef3949d3afc4ae4 and https://github.com/opensemanticsearch/open-semantic-etl/commit/6d8629ac1425f5a9b54ed50615bbba6169e077be#diff-a7b8db21f1d7da551ef3949d3afc4ae4
