### ISSUE TITLE
Dictionary based entity recognition by ontologies and SKOS thesaurus to ETL

### ISSUE THREAD

**Issue by opensemanticsearch** [opensemanticsearch/open-semantic-etl#49]
Move dictionary based entity recognition / entity extraction / entity linking by ontologies and SKOS thesaurus to ETL plugin, so we have the entities before indexing to export to Neo4j graph, too and for implementation of normalization https://github.com/opensemanticsearch/open-semantic-search/issues/20 and disambiguation.

**Comment by Mandalka** [comment]
[Dictionary based named entity extraction now done by the plugin enhance_ner_dictionary.py for Open Semantic Entity Search API](https://github.com/opensemanticsearch/open-semantic-entity-search-api) on another Solr core before indexing to the document index.
