### ISSUE TITLE
Export to Solr: Wait for reloading core

### ISSUE THREAD

**Issue by opensemanticsearch** [opensemanticsearch/open-semantic-etl#51]
Solr exporter should retry/wait instead of raising exception/indexing next file for the case the Solr core reloads (f.e. if new entries to thesaurus or ontologies and so synonyms config) - if core reload necessary after switch to Synonyms API instead of config file.

**Comment by Mandalka** [comment]
Implemented retries/waits if Solr down (connection error) or while Solr core reloads (503 temporary unavailable)
