### ISSUE TITLE
Tika 1.18: Error 500 if multiple OCR dictionaries

### ISSUE THREAD

**Issue by opensemanticsearch** [opensemanticsearch/open-semantic-etl#57]
Since upgrade to Tika 1.18 there is an server error 500 if multiple OCR dictionaries like eng+deu in headers instead of one (without plus).

**Comment by Mandalka** [comment]
Open Semantic Search builds in downloads downgraded to Tika 1.17 until issue is solved.

**Comment by Mandalka** [comment]
Fixed in Tika sources. Upgrade to newest Tika version on next relase.

**Comment by Mandalka** [comment]
In Tika 1.19.1 RC it works again.
