### ISSUE TITLE
missing py2neo when activating neo4j_export

### ISSUE THREAD

**Issue by clamor** [opensemanticsearch/open-semantic-etl#59]
the py2neo python module needs to be installed, before activating the neo4j_export plugin

**Comment by Mandalka** [comment]
Will be installed by pip3 with the new release with Neo4j integration out of the box.

**Comment by Mandalka** [comment]
Added automatic [installation of py2neo by pip](https://github.com/opensemanticsearch/open-semantic-etl/commit/8e35c613bcd9290c4e326d146cb70dc58eb60167).
