### ISSUE TITLE
neo4j_export facets

### ISSUE THREAD

**Issue by clamor** [opensemanticsearch/open-semantic-etl#60]
when activating the neo4j_export with the  open-semantic-search_18.05.04.deb installation I get a KeyError('facets',) with the following traceback when adding a file via opensemanticsearch-index-file:

` File "/usr/lib/python3/dist-packages/opensemanticetl/etl.py", line 198, in process
    parameters, data = enhancer.process(parameters=parameters, data=data)
  File "/usr/lib/python3/dist-packages/opensemanticetl/export_neo4j.py", line 34, in process
    for entity_class in parameters['facets']:`

when using the latest version of export_neo4j from github I get a KeyError('facets',) as well:

`  File "/usr/lib/python3/dist-packages/opensemanticetl/etl.py", line 198, in process
    parameters, data = enhancer.process(parameters=parameters, data=data)
  File "/usr/lib/python3/dist-packages/opensemanticetl/export_neo4j.py", line 40, in process
    for entity_class in parameters['facets']:`

**Comment by Mandalka** [comment]
The Neo4j plugin needs the facet config /etc/opensemanticsearch/facets which is automatically generated if you save an ontology, list or an facet in facet web admin interface (if you did an upgrade on existing DB / setup you can save one after an edit (even if no changes)).

The latest version in git fixes an issue, if you configured an ontology or list without setting a title/label for it, so the ID is used instead.

With todays or tomorrow release with neo4j integration out of the box this will be autogenerated on installation / upgrade.

**Comment by Mandalka** [comment]
The export of facet config for Neo4j plugin from UI DB now runs without manual start automatically on installation by https://github.com/opensemanticsearch/open-semantic-search-apps/commit/13190a95a45b115e2efa220af3ecb1aaf68ad18a and https://github.com/opensemanticsearch/open-semantic-search-apps/commit/9897d4f1f6bd27c7a1f5f5da302472b018d9d3da
