### ISSUE TITLE
Celery not indexing

### ISSUE THREAD

**Issue by yoann-mr** [opensemanticsearch/open-semantic-etl#73]
Hi,

I'm having issues with celery when using opensemanticsearch-index-dir

The first one is that it does not index documents (I'm trying to index 20 million text documents, it's been looping through them displaying "Indexing new file: ..." but there is nothing happening).

I changed the permission right to all files in the folder using chmod -R 777 /folder

Is there a log that I can look out to debug it? If I use opensemanticsearch-index-file on the folder it works.

This is the output of `celery -A proj report``

software -> celery:4.1.0 (latentcall) kombu:4.1.0 py:3.6.6
            billiard:3.5.0.3 py-amqp:2.2.2
platform -> system:Linux arch:64bit, ELF imp:CPython
loader   -> celery.loaders.app.AppLoader
settings -> transport:amqp results:disabled

CELERYD_MAX_TASKS_PER_CHILD: 1

**Comment by mosea3** [comment]
Hi Yoann

You can indeed enable some verbose variable for Debugging.
For example in /etc/opensemanticsearch/etl, remove the comment brackets on top of the file.

There you will have a full verbose of python, solr, tika etc.

Maybe, an activated but misconfigured OCR, is eating up all resources?
Check with unix command top for bottlenecks during an indexing process

Best regards

Andy


Hi,

I'm having issues with celery when using opensemanticsearch-index-dir

The first one is that it does not index documents (I'm trying to index 20 million text documents, it's been looping through them displaying "Indexing new file: ..." but there is nothing happening).

I changed the permission right to all files in the folder using chmod -R 777 /folder

Is there a log that I can look out to debug it? If I use opensemanticsearch-index-file on the folder it works.

This is the output of `celery -A proj report``

software -> celery:4.1.0 (latentcall) kombu:4.1.0 py:3.6.6
billiard:3.5.0.3 py-amqp:2.2.2
platform -> system:Linux arch:64bit, ELF imp:CPython
loader -> celery.loaders.app.AppLoader
settings -> transport:amqp results:disabled

CELERYD_MAX_TASKS_PER_CHILD: 1

**Comment by yoann-mr** [comment]
Thanks Andy!

I'll give it a try.
