### ISSUE TITLE
Optimize performance of entity extraction

### ISSUE THREAD

**Issue by opensemanticsearch** [opensemanticsearch/open-semantic-etl#74]
- Merge index segments https://github.com/opensemanticsearch/open-semantic-entity-search-api/issues/36
- Do not analyze technical meta data fields

**Comment by opensemanticsearch** [comment]
Exclusion of technical meta data fields will be solved by https://github.com/opensemanticsearch/open-semantic-etl/issues/112

**Comment by Mandalka** [comment]
Merging index segments now by Solr optimize after Ontologies import by Django App Ontologies Manager.
