### ISSUE TITLE
The command opensemanticsearch-index-dir <dir with trailing slash> reindex the directory

### ISSUE THREAD

**Issue by maurizio-emmex** [opensemanticsearch/open-semantic-etl#8]
I use the VM for indexing a pair samba share.
I index a directory with the command `# opensemanticsearch-index-dir -v /mnt/f/FAX` .
If, after the above command,  I will run `# opensemanticsearch-index-dir -v /mnt/f/FAX/` the directory will be indexed again.
Searching for a single document I receive a double result, eg. for Fax0000017c.TIF I obtain:
file:///f:/FAX/Fax0000017c.TIF
file:///f:/FAX//Fax0000017c.TIF

**Comment by Mandalka** [comment]
Tnx for bug report. [Fixed](https://github.com/opensemanticsearch/open-semantic-etl/commit/cc47d67fd5155d2aa3484be09304e634512f5d68), so both variants will be considered as same filenames.
