### ISSUE TITLE
Retry / Wait for micro services REST-APIs like Tika server

### ISSUE THREAD

**Issue by opensemanticsearch** [opensemanticsearch/open-semantic-etl#84]
If system rebooted while ETL, the Celery / RabbitMQ message queue / ETL tasks start to run even if the needed services like Tika or Spacy Services not started yet, so some files are indexed without content or analysis.

Wait until all dependent services up / retry / wait.

**Comment by Mandalka** [comment]
Startup of ETL task workers waits until this services are up.

Todo: Wait / Retry if one of the services is down/restarted.

**Comment by Mandalka** [comment]
The ETL plugin for text extraction by Tika server waits & retries until Tika server / Microservice / REST-API is up (again).

**Comment by Mandalka** [comment]
Files/documents are reindexed, if yet ETL / indexed when Tika was down.

**Comment by Mandalka** [comment]
ETL plugin for language detection by Tika server waits & retries until Tika server / Microservice / REST-API is up (again).

**Comment by Mandalka** [comment]
ETL plugin for Named Entity Recognition by Spacy waits & retries until Spacy services / Microservice / REST-API is up (again).

**Comment by Mandalka** [comment]
ETL plugin for Named Entity Extraction and Entity Linking by Solr text tagger waits & retries until Solr HTTP service is up (again) and loaded the core (meanwhile 503 for service temporary unavailable).

**Comment by opensemanticsearch** [comment]
Todos:

Wait for Spacy services in sentence segmentation plugin.

Wait for Solr exporter (which otherwise is not critical since ETL will be repeated because otherwise document not in index).

**Comment by Mandalka** [comment]
Implemented retries/waits if Solr down (connection error) or while Solr core reloads (503 temporary unavailable)

**Comment by Mandalka** [comment]
Implemented retries/wait in sentence segmentation plugin if Spacy services down.
