### ISSUE TITLE
Upgrade to Spacy 2.1

### ISSUE THREAD

**Issue by opensemanticsearch** [opensemanticsearch/open-semantic-etl#85]
Upgrade to newest Spacy and spacy-services

**Comment by Mandalka** [comment]
Upgraded Spacy Services in https://github.com/opensemanticsearch/spacy-services.deb/commit/60297007dda423ef065e350ef969ce492b4df4bc and Open Semantic ETL to new REST-API in https://github.com/opensemanticsearch/open-semantic-etl/commit/f3e0c7305af2ca2fafd7cd4aad7d7e8175221c27
