### ISSUE TITLE
PIP requirements

### ISSUE THREAD

**Issue by opensemanticsearch** [opensemanticsearch/open-semantic-etl#92]
Define Python package dependencies from Debian package to PIP requirements.txt for easier installation by [automatic resolution of dependencies](https://github.com/opensemanticsearch/open-semantic-search/issues/193) on non Debian Systems.

**Comment by Mandalka** [comment]
Moved Python dependencies from DEBIAN/postinst to more platform independent pip config requirements.txt so it can be used while building Docker container, too.

Todo: Add all other Python packages dependecies from DEBIAN/control to requirements.txt for automatic dependencies resolution on non-debian and non-ubuntu installations, too.

**Comment by Mandalka** [comment]
Added all Python packages from DEBIAN/control to requirements.txt
