### ISSUE TITLE
Automated tests

### ISSUE THREAD

**Issue by opensemanticsearch** [opensemanticsearch/open-semantic-etl#94]
Automated tests by Python unittest

**Comment by Mandalka** [comment]
Added first automated test by Python unittest for etl_file.py in test_etl_file.py which automatically tests the extraction of text and title from test.pdf by Tika and the OCR of embedded PNG and JPG by tesseract plugin.

**Comment by Mandalka** [comment]
Added separated unittest for Tika plugin for text extraction.

**Comment by Mandalka** [comment]
Added separated unittest for OCR of embedded images in PDF files and for descewing by Scantailor.

**Comment by Mandalka** [comment]
Added check for ETL file, if a plugin threw an uncaught exception.

**Comment by Mandalka** [comment]
Added tests for Spacy NER plugin with test sentences for English and German.

**Comment by Mandalka** [comment]
Added documentation to https://github.com/opensemanticsearch/open-semantic-etl/blob/master/src/opensemanticetl/test/README.md

**Comment by Mandalka** [comment]
Added tests and test images for OCR of JPG and PNG and diabling OCR by Tika plugin (using Tika server).

**Comment by Mandalka** [comment]
Implemented automated tests for adding entities to Solr index by entity manager and extract from full text by Solr text tagger/normalize/link it by entity linker in [unittest of Open Semantic Entity Search API](https://github.com/opensemanticsearch/open-semantic-entity-search-api/issues/39).

**Comment by Mandalka** [comment]
Added tests for plugin for mapping of IDs/URLs/Paths.

**Comment by Mandalka** [comment]
Added tests for language detection plugin.

**Comment by Mandalka** [comment]
Added tests for email address extraction and email domain extraction plugin.

**Comment by Mandalka** [comment]
Added test for import of file from WARC web archive format.

**Comment by Mandalka** [comment]
Added tests for enhance_ocr_descew for descewing by scantailor and OCR by tesseract

**Comment by Mandalka** [comment]
Added full stack integration tests by docker-compose.etl.test.yml

**Comment by Mandalka** [comment]
More yet not available unittests for some modules while further TDD.
