### ISSUE TITLE
How to disable Cron email alert.

### ISSUE THREAD

**Issue by scarabator** [opensemanticsearch/open-semantic-etl#96]
Hello, 

How to disable "**Cron curl --silent http://localhost/search-apps/rss_manager/import**" email alert, I have an email every minute and Google blocks me the other applications ressources because I get the following message: Daily user sending quota exceeded.  - gsmtp.

Thank you for your help.

**Comment by Mandalka** [comment]
https://github.com/opensemanticsearch/open-semantic-search-apps/commit/60d1888e76a8b75c806e05f5fd715edb7d363938 (will be included in next relase) should do it.
