### ISSUE TITLE
Where is spacy entity linking trained model?

### ISSUE THREAD

**Issue by StudyExchange** [opensemanticsearch/open-semantic-etl#98]
**Where is spacy entity linking trained model?**
This project have entity linking feature suported by spacy, but I do not find spacy entity linking model. As I know, spacy entity linking model need trained by ourself, there is no official released version. How did you implement entity linking feature.

**Comment by Mandalka** [comment]
There are some official released models which are used here without changes

Open Semantic ETL chooses a single model dependent on document language (mapping of languages to model in ETL config, so you can setup own models if trained some).

Implementation of REST-API is in spacy-services. That service is used by our ETL plugin https://github.com/opensemanticsearch/open-semantic-etl/blob/master/src/opensemanticetl/enhance_ner_spacy.py

The standard spacy models are installed by Pip by following requirements config to your local python lib path used for pip installations:

https://github.com/explosion/spacy-services/blob/master/displacy/requirements.txt
https://github.com/opensemanticsearch/spacy-services/blob/master/displacy/requirements.txt
